// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5GMfF3SgsnmmUCCdm5eRr4vfdMvqfQuc',
    appId: '1:703177151510:web:0d0db0d79d27eddc411137',
    messagingSenderId: '703177151510',
    projectId: 'waheed-foods',
    authDomain: 'waheed-foods.firebaseapp.com',
    storageBucket: 'waheed-foods.firebasestorage.app',
    measurementId: 'G-RXVP3XDLG5',
    databaseURL: 'https://waheed-foods-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqmqe5uo3TcxKLymYnw3uPEEtqSmCpZ44',
    appId: '1:703177151510:android:f88e50a985d1c0f5411137',
    messagingSenderId: '703177151510',
    projectId: 'waheed-foods',
    storageBucket: 'waheed-foods.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBAEyjCMkltE7HEE7U4UiUEpev1i9Q4vA',
    appId: '1:703177151510:ios:285326609d9a6821411137',
    messagingSenderId: '703177151510',
    projectId: 'waheed-foods',
    storageBucket: 'waheed-foods.firebasestorage.app',
    iosBundleId: 'com.example.waheedFoods',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBAEyjCMkltE7HEE7U4UiUEpev1i9Q4vA',
    appId: '1:703177151510:ios:285326609d9a6821411137',
    messagingSenderId: '703177151510',
    projectId: 'waheed-foods',
    storageBucket: 'waheed-foods.firebasestorage.app',
    iosBundleId: 'com.example.waheedFoods',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5GMfF3SgsnmmUCCdm5eRr4vfdMvqfQuc',
    appId: '1:703177151510:web:47b36d8b858d1a41411137',
    messagingSenderId: '703177151510',
    projectId: 'waheed-foods',
    authDomain: 'waheed-foods.firebaseapp.com',
    storageBucket: 'waheed-foods.firebasestorage.app',
    measurementId: 'G-VNNQQWPCY0',
  );

}